# Generated by Django 5.1.2 on 2024-10-20 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='destinationsApp.user'),
            preserve_default=False,
        ),
    ]
