# Generated by Django 5.1.2 on 2024-10-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationsApp', '0002_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='destination',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(unique=True),
        ),
    ]
