# Generated by Django 5.1.1 on 2024-09-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
