# Generated by Django 5.1.1 on 2024-09-26 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0002_activity_name_alter_activity_id_alter_timelog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
